### ISSUE TITLE
Application Standard

### ISSUE THREAD

**Issue by praswicaksono** [MalangPHP/singo-app#6]
- Swagger for API Spec
- Modular Architecture
- Command Design Pattern
- Annotation Routing

**Comment by santosoide** [comment]
IoC Container itu sudah masuk bagian mana? Command Design Pattern

**Comment by praswicaksono** [comment]
Container udah bawaan silex nya mas jadi fitur default silex ga tak masukin sebagai standard.

Command Design Pattern itu Command Handler pake library tactician untuk lebih jelas : https://sourcemaking.com/design_patterns/command

**Comment by reyhansofian** [comment]
Swagger UI ga masuk? atau optional aja?

**Comment by reyhansofian** [comment]
Apa perlu kita pke dotenv library untuk define environment nya?
https://github.com/vlucas/phpdotenv

**Comment by praswicaksono** [comment]
iyo mas swagger sak UI e pastine

bedane karo file config opo mas?

**Comment by santosoide** [comment]
Oh ya ntar ada fitur detect env?, pakai file .env yang disebutkan sam @reyhansofian itu lebih simple, dipakai di L5

**Comment by santosoide** [comment]
misal gini lah nanti confignya : 

```
APP_ENV=local
APP_DEBUG=true
APP_KEY=TEEmkCacdp03ShF1Vx2C94Qefomb3i4R

DB_HOST=localhost
DB_DATABASE=officepage
DB_USERNAME=homestead
DB_PASSWORD=secret

CACHE_DRIVER=redis
SESSION_DRIVER=redis
QUEUE_DRIVER=beanstalkd

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
```

**Comment by reyhansofian** [comment]
Jangan lupa built in webserver :smile:

**Comment by praswicaksono** [comment]
kalo menurutku masih enak pake yaml, langsung di konversi jadi array bisa nested

contohnya untuk konfigurasi module

```
modules:
  base_namespace: Singo\Tests\Modules
  modules:
    -
      Main:
        controllers:
          /:
            - IndexController
    -
      User:
        controllers:
          /user:
            - UserController
```

langsung di parsing jadi array tinggal register module satu satu
